</center>
<center>
<?php
include 'includes/site_info.inc';
?>
<font size=2>Copyright &copy; 2008 - 2013 <a href="http://www.fixyourip.com">www.fixyourip.com</a>.</font>
</center>


<!-- Google add 1 button -->
<script type="text/javascript" src="http://apis.google.com/js/plusone.js"></script>

<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-744038-6', 'auto');
  ga('send', 'pageview');

</script>

<! -- End Google Analytics -->

<!-- Begin Oreilly advertising -->
<script src="http://www.anrdoezrs.net/am/7724844/include/allCj/am.js"></script>
<!-- End advertising -->
<input type='hidden' value='accupub.org/iDHhxGtbK71xApSmx96z8rShYF' />

</body>
</html>
