<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Types of Certificates</title>
<meta name="keywords" content="certificates,display thumbprint, view digital thumprint, view issuer of certificate, view certificate subject, view certificate expiry date, view certificate purpose, view certificate public key" />
<meta name="description" content="view certificate, examine your ssl certificate" />
<meta name="author" content="Webmaster"/>
<META HTTP-EQUIV="CACHE-CONTROL: max-age=86400, must-revalidate"/>
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
