<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Free Public DNS Servers</title>
<meta name="keywords" content="List of Public DNS Servers, public dns servers, public dns server, public caching server, free dns servers,dns servers" />
<meta name="description" content="List of free public dns servers" />
<meta name="author" content="Webmaster"/>
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="must-revalidate"/>
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
