<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>DNS Records</title>
<meta name="keywords" content="A record, mx record, cname record, txt record,ns record, online dns lookup tool," />
<meta name="description" content="List of DNS abbreviations" />
<meta name="author" content="Webmaster"/>
<META HTTP-EQUIV="CACHE-CONTROL: max-age=86400, must-revalidate"/>
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
